### ISSUE TITLE
移动端 BUG

### ISSUE THREAD

**Issue by P3TERX** [MeowCat-Studio/MeowPassword#1]
![1](https://user-images.githubusercontent.com/25927179/61109697-14b73700-a4b8-11e9-80ac-7a32be40d7e1.gif)

密码长度的滑块滑动时数字不会改变，放手后才会改变。

布局有点乱，按钮和文字重叠了。

Chrome 浏览器

**Comment by MlgmXyysd** [comment]
那个文字。。。写的有点长了，回来多语言系统在搞他，按钮是在文本框末尾的
那个滑动bug目测是jquery在手机端没检测到mouse移动事件，放手后改变检测的是onchange事件

**Comment by MlgmXyysd** [comment]
#2 应该修复了，我这边电脑模拟移动端点击事件可以了。

**Comment by P3TERX** [comment]
![TIM图片20180116175226](https://user-images.githubusercontent.com/25927179/61760629-c3d00880-adfe-11e9-8edd-c0409e566db8.jpg)
感谢大佬！没问题了。
